version: "3.8"

services:
  server:
    image: todo-backend
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://the_username:the_password@mongo/the_database
    command: npm run dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db

  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
